version: '2'

services:

### Workspace Utilities Container ###########################
    jobthai-bof:
        image: registry.thinknet.co.th/sredev/node:8.9
        ports:
            - "8080:8080"
        volumes:
            - .:/usr/src/app
        command: ['/bin/sh', '-c', 'yarn && yarn dev']
networks:
    default:
        external:
            name: microservicenetwork